### ISSUE TITLE
로그인 오류

### ISSUE THREAD

**Issue by rkdwldns00** [Neonlight-Repo/MMOServer#1]
클라이언트를 종료 후 서버를 끄지 않고 다시 로그인 할 경우 이미 접속하고있는 유저가 있다고 뜨면서 로그인이 안됩니다.
클라이언트 브랜치 : Feature-PlayerLogic

**Comment by index1207** [comment]
버그 재현:
회원가입 후 회원가입한 계정으로 로그인 시 플레이어가 null이 되는 애러 발생

버그 픽스:
AccountServer에서 회원 가입 후 로그인 할 시 db정보 새로고침이 되지 않아 발생함
회원가입한 후 서버에서 갱신시키는 방법으로 애러 해결
