### ISSUE TITLE
6번 로그인 오류

### ISSUE THREAD

**Issue by rkdwldns00** [Neonlight-Repo/MMOServer#2]
![image](https://github.com/Neonlight-Repo/MMOServer/assets/46744270/a83aca1b-7818-4b21-b912-101350b98b27)
6번 로그인, 월드 입장을 한 뒤, 클라이언트를 종료하면 서버에서 튕김
클라이언트는 PlayerLogic 브랜치

**Comment by index1207** [comment]
버그 재현: 6번 로그인 후 퇴장
버그 원인: 다른 스레드에서의 참조 카운트에 의해 `Session`의 수명이 다해 `shared_from_this`에서 null을 참조한 것이 원인
