### ISSUE TITLE
채팅 전송 및 수신 오류

### ISSUE THREAD

**Issue by ysk102706** [Neonlight-Repo/MMOServer#5]
### Description

클라이언트 몇 개든 상관없이 채팅을 보낼 시 서버 오류

### Callstack

![image](https://github.com/Neonlight-Repo/MMOServer/assets/105967323/1e54ff92-49c5-4100-8fde-a24a2ed2848a)

### Steps To Reproduce

1. 클라이언트 실행
2. '/a message' 형태로 메시지 입력 후 엔터
3. 엔터 후 바로 오류 발생

**Comment by index1207** [comment]
브렌치도 알려주세요

**Comment by ysk102706** [comment]
Feature-UI 입니다
